env:
    # fushar's auth token
    - secure: "yTjvOKfgq11N2G/BbA3tFxwKPwn4Ykh1dF4pQ2w4394hXwzsbrhhRVy4Q85z5JJ8r5xAmUzxefwpgSA0cQJ6ovhXW2paU1utxZRWLbBm+p7K9MiaStpX7eRtCU7whUYUsKsLHwgjxg89V7/Vlsv6/MqIk6lStB2utkcH90l5fJQ="

before_install:
    - sudo apt-get update
    - wget launchpadlibrarian.net/128239195/latexmk_4.35-0ubuntu1_all.deb

install:
    - sudo apt-get install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended
    - sudo dpkg -i latexmk_4.35-0ubuntu1_all.deb
    - sudo ./setup.sh

script:
    - make

after_success:
    - ./publish_pdf.sh
